"""empty message

Revision ID: 3899863b0bd8
Revises: 252f1f4c704d
Create Date: 2024-10-16 16:16:52.034878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3899863b0bd8'
down_revision: Union[str, None] = '252f1f4c704d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('account_id', sa.Integer(), nullable=False))
    op.add_column('bank_accounts', sa.Column('balance', sa.Numeric(precision=10), nullable=False))
    op.drop_column('bank_accounts', 'name')
    op.drop_column('bank_accounts', 'description')
    op.drop_column('bank_accounts', 'id')
    op.add_column('orders', sa.Column('order_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('total_amount', sa.Numeric(precision=10), nullable=False))
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['customer_id'], ['id'])
    op.drop_column('orders', 'total')
    op.drop_column('orders', 'id')
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('orders', sa.Column('total', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'])
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'customer_id')
    op.drop_column('orders', 'order_id')
    op.add_column('bank_accounts', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('bank_accounts', sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('bank_accounts', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('bank_accounts', 'balance')
    op.drop_column('bank_accounts', 'account_id')
    # ### end Alembic commands ###
